name: Pull Request CI
on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm prettier --check src/**
      - run: pnpm lint
      - run: pnpm tsc
      - run: pnpm build
      # - uses: GabrielBB/xvfb-action@v1.6
      #   with:
      #     run: pnpm integration-test
